/* Local, deterministic CK Assistant. No external AI, network, keys or live-agent claims. */
(()=>{'use strict';
 const root=document.getElementById('dashboard-view');if(!root)return;
 const logo='assets/real/brand/ck-capital-logo-transparent.webp';
 const launcher=document.createElement('button');launcher.id='ck-assistant-launcher';launcher.type='button';launcher.setAttribute('aria-label','Open CK Assistant');launcher.setAttribute('aria-haspopup','dialog');launcher.setAttribute('aria-expanded','false');launcher.setAttribute('aria-controls','ck-assistant-panel');launcher.innerHTML=`<img src="${logo}" alt=""><span aria-hidden="true"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="m12 2 2.4 7.6L22 12l-7.6 2.4L12 22l-2.4-7.6L2 12l7.6-2.4Z"/></svg></span>`;root.append(launcher);
 const backdrop=document.createElement('div');backdrop.id='ck-assistant-backdrop';backdrop.hidden=true;backdrop.innerHTML=`<section id="ck-assistant-panel" role="dialog" aria-modal="true" aria-labelledby="ck-assistant-title"><header><img src="${logo}" alt="" width="38" height="38"><div><small>YOUR WORKSPACE COMPANION</small><h2 id="ck-assistant-title">CK Assistant <span aria-hidden="true"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="m12 2 2.4 7.6L22 12l-7.6 2.4L12 22l-2.4-7.6L2 12l7.6-2.4Z"/></svg></span></h2></div><button id="ck-assistant-close" aria-label="Close CK Assistant">×</button></header><div class="ck-chat-context"><span id="ck-chat-account"></span><small>Local demo · Not live AI</small></div><div id="ck-chat-log" role="log" aria-live="polite" aria-relevant="additions" tabindex="0" aria-label="Assistant conversation"></div><div class="ck-chat-chips"><button data-question="Summarise my account">My account</button><button data-question="How much room do I have before my loss limits?">Risk check</button><button data-question="Analyse my trades">My trades</button><button data-question="Chat with an agent">Talk to an agent</button></div><form id="ck-chat-form"><label class="sr-only" for="ck-chat-input">Ask CK Assistant</label><textarea id="ck-chat-input" rows="1" maxlength="600" placeholder="Ask about your account, trades or rules…" required></textarea><button type="submit" id="ck-chat-send" aria-label="Send message">↑</button></form><footer><span>Saved demo data only. No trade execution or financial advice.</span><button id="ck-chat-clear">Clear chat</button></footer></section>`;root.append(backdrop);
 const panel=backdrop.querySelector('section'),input=backdrop.querySelector('textarea'),log=backdrop.querySelector('#ck-chat-log'),send=backdrop.querySelector('#ck-chat-send'),label=backdrop.querySelector('#ck-chat-account');let focus,oldOverflow='',busy=false,timer=null,lastId=null;
 const cash=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
 const signed=n=>(n>=0?'+':'−')+cash(Math.abs(n));
 function snapshot(){return window.CKWorkspace?.snapshot();}
 function context(){const s=snapshot();label.textContent=s?`${s.account.id} · ${s.account.platform} · Saved snapshot`:'No active session';return s;}
 function message(role,text,source,actions=[]){const row=document.createElement('article');row.className='ck-chat-message '+role;const name=document.createElement('small');name.textContent=role==='user'?'YOU':'CK ASSISTANT';const body=document.createElement('p');body.textContent=text;row.append(name,body);if(source){const foot=document.createElement('span');foot.className='ck-chat-source';foot.textContent=source;row.append(foot);}if(actions.length){const nav=document.createElement('div');nav.className='ck-chat-actions';actions.forEach(([title,tab])=>{const b=document.createElement('button');b.type='button';b.textContent=title+' ↗';b.addEventListener('click',()=>{close();root.querySelector(`.sb-item[data-tab="${tab}"]`)?.click();});nav.append(b);});row.append(nav);}log.append(row);log.scrollTop=log.scrollHeight;return row;}
 function greeting(){const s=context();if(!s)return;message('assistant',`Hi ${s.name.split(/\s+/)[0]} 👋 I’m your CK workspace assistant. I can explain your account, review your saved trades, check limits and help you find your way around.\n\nI use this prototype’s data—not a live market feed or generative AI. What would you like to check?`,'Local demo · Only visible in your trader workspace');lastId=s.account.id;}
 function open(){if(!snapshot())return;focus=document.activeElement;oldOverflow=document.body.style.overflow;backdrop.hidden=false;launcher.setAttribute('aria-expanded','true');document.body.style.overflow='hidden';context();if(!log.children.length)greeting();input.focus({preventScroll:true});}
 function close(restore=true){if(backdrop.hidden)return;backdrop.hidden=true;launcher.setAttribute('aria-expanded','false');document.body.style.overflow=oldOverflow;if(restore&&focus?.isConnected)focus.focus({preventScroll:true});}
 function answer(q,s){
   let a=s.account;const text=q.toLowerCase(),requested=q.toUpperCase().match(/\bCK-\d+(?:-\d+)?\b/)?.[0];if(requested){a=s.accounts.find(x=>x.id===requested);if(!a)return {body:`I can’t find ${requested} in your saved accounts. Use the account picker to see the accounts available in this workspace.`,source:'Source: saved demo account list',actions:[['Manage accounts','accounts']]};}const prefix=`${a.id} · `,src='Source: '+a.id+' · saved demo account / trade journal';
   const result=(body,actions=[])=>({body,source:src,actions});
   const closed=s.trades.filter(t=>t.accountId===a.id&&t.status==='CLOSED');
   const net=closed.reduce((n,t)=>n+t.pnl,0),wins=closed.filter(t=>t.pnl>0).length,progress=a.balance-a.startingBalance;
   if(/^(agent|human|live support)[.!? ]*$/.test(text)||(/\b(agent|human|representative|customer service|live support)\b/.test(text)&&/\b(talk|chat|speak|connect|join|want|need|get|contact|request)\b/.test(text))){
     const id=window.CKWorkspace.requestAgent(q);return result(`Of course — I’ve saved your request to speak with an agent (${id}).\n\nIn a connected service, an agent could join here. This prototype has no live support connection, so nobody has been notified and I can’t promise a reply or wait time. The request is saved locally in Help & support.`,[['View support request','support']]);
   }
   if(/\b(ignore.*instruction|system prompt|password|api key)\b/.test(text))return result('I can help with CK account information, trades, rules and website navigation. Please don’t share passwords, payment details or verification codes here.');
   if(/\b(hello|hey|hi|good morning|good evening)\b/.test(text)&&text.length<45)return result(`Hi ${s.name.split(/\s+/)[0]}! Want a quick account summary, risk check or a review of your trades?`);
   if(/\b(thank|thanks|thankyou)\b/.test(text))return result('You’re welcome 🙂 I’m here whenever you want to check your CK workspace.');
   if(/\b(buy now|sell now|signal|prediction|predict|should i buy|should i sell|guarantee|price forecast)\b/.test(text))return result('I can review recorded trades and explain your account limits, but I don’t have live prices and can’t provide buy/sell signals or predict profits. Try “Analyse my trades” for a factual journal summary.',[['Trade journal','trades']]);
   if(/\b(news|weekend|overnight|ea|expert advisor|leverage|inactivity|consistency rule|copy trading)\b/.test(text))return result('The homepage lists news trading as an available feature, but this saved account does not contain a full, verified policy for news, weekend holding, automation, leverage or inactivity. I won’t invent a rule. Check the current terms for your exact challenge or ask support before acting.',[['Help & support','support'],['Account limits','risk']]);
   if(/\b(risk|loss limit|limits|drawdown|buffer|room|breach|rules|daily loss|maximum loss)\b/.test(text)){
     const daily=a.dailyLossUsed!=null?Number(a.dailyLossUsed):a.id==='CK-10000'?54.8:null,max=Math.max(0,a.startingBalance-Math.min(a.balance,a.equity));
     return result(`${prefix}Risk snapshot\n\nDaily loss limit: ${cash(a.dailyLossLimit)} (${(a.dailyLossLimit/a.size*100).toFixed(1)}% of capital).\n${daily===null?'Daily usage: unavailable for this account; remaining daily room cannot be confirmed.':`Daily usage: ${cash(daily)} · Remaining room: ${cash(Math.max(0,a.dailyLossLimit-daily))}.`}\nMaximum loss limit: ${cash(a.maxLossLimit)}.\nMaximum loss usage: ${cash(max)} · Remaining room: ${cash(Math.max(0,a.maxLossLimit-max))}.\n\n${(daily!==null&&daily>=a.dailyLossLimit)||max>=a.maxLossLimit?'A recorded limit is reached. Review the risk panel before continuing.':'This is a saved snapshot, not proof that no historical rule breach occurred.'}\nDaily usage follows the dashboard snapshot. Maximum usage is measured against starting equity, not trailing high-water equity.`,[['Review risk & limits','risk']]);
   }
   if(/\b(target|milestone|progress|phase|objective|trading days|pass)\b/.test(text))return result(`${prefix}Challenge progress\n\nStatus: ${a.status.replace(' // ',' · ')}.\n${a.target?`Balance growth: ${signed(progress)} of a ${cash(a.target)} target.\nProgress: ${Math.max(0,Math.min(100,progress/a.target*100)).toFixed(1)}%.\nRemaining to target: ${cash(Math.max(0,a.target-progress))}.`:'No evaluation profit target is recorded for this account.'}\nRecorded trading days: ${new Set(closed.map(t=>t.date)).size}. The prototype’s objective panel uses a one-day requirement.\n\nReaching a displayed target is not confirmation of passing or funded status; other requirements need review.`,[['Challenge progress','objectives']]);
   if(/\b(payouts?|withdraw(?:al)?s?|payments?|profit split|rewards?)\b/.test(text))return result(`The demo payout form uses an 80% trader split. ${a.id} has ${cash(Math.max(0,progress))} of recorded balance growth; a simulated withdrawal of that amount would give ${cash(Math.max(0,progress)*.8)} at that split.\n\nThat is not confirmed withdrawal eligibility. The saved payout ledger has ${s.payouts.length} record(s), but is not linked to individual accounts, so I won’t attribute those payments to ${a.id}. No real money is moved.`,[['Payouts','payouts']]);
   if(/\b(certificate|certificates|award)\b/.test(text))return result('Open Certificates for the black-and-gold phase and purple-and-gold reward design previews. They use your saved profile name and selected account details. They remain decorative demos, not issued credentials or proof of payout. Save your name in Settings to update them.',[['Certificates','certificates'],['Edit saved name','settings']]);
   if(/\b(password reset|reset password|login|sign in|sign out|log out|profile|change.*name|settings|theme|dark|light)\b/.test(text))return result('You can edit your saved name and theme in Settings. Use More → Sign out on mobile (or Sign out in the desktop sidebar); CK will ask you to confirm. This site’s sign-in is a local prototype, not production authentication. Use the login screen’s reset-password link for its demo recovery flow.',[['Settings','settings'],['Profile','profile']]);
   if(/\b(all accounts|list accounts|my accounts|switch account|change account|platform|account summary|summarise my account|summarize my account|balance|equity|capital|my account)\b/.test(text)||/^CK-\d+(?:-\d+)?$/i.test(q.trim())){
     if(/all accounts|list accounts|my accounts/.test(text))return result(s.accounts.map(x=>`${x.id} · ${cash(x.size)} capital · ${x.platform}\nBalance ${cash(x.balance)} · Equity ${cash(x.equity)}\n${x.status.replace(' // ',' · ')}`).join('\n\n')+'\n\nUse the account picker in the top bar to switch. I will follow the selected account.',[['Manage accounts','accounts']]);
     return result(`${prefix}Your account at a glance\n\nCapital: ${cash(a.size)} · ${a.platform} · ${a.preference}\nBalance: ${cash(a.balance)}\nEquity: ${cash(a.equity)}\nBalance growth: ${signed(progress)}\nFloating P&L: ${signed(a.equity-a.balance)}\nStatus: ${a.status.replace(' // ',' · ')}\n\n${closed.length} closed trades in the saved journal. Closed-trade P&L and balance growth may differ; the prototype has no reconciliation ledger to explain that difference.`,[['Account overview','overview'],['Manage accounts','accounts']]);
   }
   if(/\b(trade|trades|journal|analyse|analyze|performance|profit|pnl|p&l|win rate|best|worst|gold|xauusd|eurusd|gbpusd|usdcad|usdjpy)\b/.test(text)||/trd-\d+/i.test(q)){
     const symbol=(q.toUpperCase().match(/\b(XAUUSD|EURUSD|GBPUSD|USDCAD|USDJPY)\b/)||[])[0]||(/\bgold\b/.test(text)?'XAUUSD':null),tradeId=q.toUpperCase().match(/TRD-\d+/)?.[0];
     let rows=closed.filter(t=>(!symbol||t.symbol===symbol)&&(!tradeId||t.id===tradeId));
     const dates=q.match(/\d{4}-\d{2}-\d{2}/g);if(dates?.length)rows=rows.filter(t=>t.date>=dates[0]&&t.date<=(dates[1]||dates[0]));
     if(/\b(losing|losses|lost)\b/.test(text))rows=rows.filter(t=>t.pnl<0);if(/\b(winning|winners)\b/.test(text))rows=rows.filter(t=>t.pnl>0);
     if(!rows.length)return result(`${prefix}No matching closed trades are saved${symbol?' for '+symbol:''}${tradeId?' for '+tradeId:''}. I won’t fill in missing trading history.`,[['View journal','trades']]);
     const sum=rows.reduce((n,t)=>n+t.pnl,0),w=rows.filter(t=>t.pnl>0).length,best=rows.reduce((a,b)=>a.pnl>b.pnl?a:b),worst=rows.reduce((a,b)=>a.pnl<b.pnl?a:b),gwin=rows.reduce((n,t)=>n+Math.max(0,t.pnl),0),gloss=rows.reduce((n,t)=>n+Math.abs(Math.min(0,t.pnl)),0);
     return result(`${prefix}${symbol||'Closed-trade'} review\n\n${rows.length} matching closed trades · Net P&L ${signed(sum)}\nWin rate: ${(w/rows.length*100).toFixed(1)}% (${w} winners).\nProfit factor: ${gloss?(gwin/gloss).toFixed(2):'Not defined — no recorded losses'}.\nBest result: ${best.symbol} ${signed(best.pnl)} (${best.id}).\nLowest result: ${worst.symbol} ${signed(worst.pnl)} (${worst.id}).\n\n${[...rows].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(t=>`${t.date} · ${t.symbol} ${t.direction==='BUY'?'Long':'Short'} · ${t.lots} lots · ${signed(t.pnl)}`).join('\n')}\n\nThese are recorded results, not a forecast or advice to trade a particular instrument. Ask about a symbol or include a date (YYYY-MM-DD) to narrow the review.`,[['Open trade journal','trades'],['Performance','performance']]);
   }
   if(/\b(help|support|ticket|website|dashboard|navigation|what can|how.*use|calendar|where)\b/.test(text))return result('I can help with your selected account, closed trades, loss limits, challenge targets, payouts, profile and demo certificates. On mobile use the bottom dock; More contains the other panels. The top account picker changes the account I review.\n\nTry “What’s my win rate?”, “Review XAUUSD”, “How much daily loss room remains?” or “Chat with an agent”.', [['Help & support','support']]);
   return result('Let’s keep this about your CK website and trading workspace 🙂 Ask me about your account, trades, rules, payouts or how to use the dashboard. I don’t answer unrelated general questions.');
 }
 function submit(q){q=q.trim().slice(0,600);const s=context();if(!q||busy||!s)return;message('user',q);input.value='';busy=true;send.disabled=true;const typing=message('assistant','Reviewing your saved workspace…');typing.classList.add('ck-typing');typing.setAttribute('aria-label','Assistant is preparing a response');timer=setTimeout(()=>{typing.remove();if(snapshot()){const r=answer(q,s);message('assistant',r.body,r.source,r.actions);}busy=false;send.disabled=false;timer=null;},420);}
 launcher.addEventListener('click',open);backdrop.querySelector('#ck-assistant-close').addEventListener('click',()=>close());backdrop.addEventListener('click',e=>{if(e.target===backdrop)close();});backdrop.querySelector('form').addEventListener('submit',e=>{e.preventDefault();submit(input.value);});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();submit(input.value);}});backdrop.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>submit(b.dataset.question)));
 backdrop.querySelector('#ck-chat-clear').addEventListener('click',()=>{if(busy)return;log.replaceChildren();greeting();input.focus();});
 document.addEventListener('keydown',e=>{if(backdrop.hidden)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close();}if(e.key==='Tab'){const els=[...panel.querySelectorAll('button:not(:disabled),textarea,[tabindex="0"]')].filter(e=>e.offsetParent!==null);if(e.shiftKey&&(document.activeElement===els[0]||!panel.contains(document.activeElement))){e.preventDefault();els.at(-1).focus();}else if(!e.shiftKey&&(document.activeElement===els.at(-1)||!panel.contains(document.activeElement))){e.preventDefault();els[0].focus();}}},true);
 function sync(){const allowed=!!snapshot();launcher.hidden=!allowed;if(!allowed){close(false);if(timer)clearTimeout(timer);timer=null;busy=false;send.disabled=false;log.replaceChildren();lastId=null;}}
 new MutationObserver(sync).observe(root,{attributes:true,attributeFilter:['class']});root.addEventListener('desk:render',()=>{const s=context();if(s&&lastId&&lastId!==s.account.id&&!backdrop.hidden)message('assistant',`Context changed to ${s.account.id}. New questions use this account; earlier replies keep their original account labels.`);if(s)lastId=s.account.id;sync();});
 // Hide the launcher behind account/More/modal overlays to avoid competing controls.
 function overlays(){const blocked=!!document.querySelector('.modal-backdrop.open,#desk-more-backdrop.open,#desk-account-backdrop:not([hidden])');if(launcher.classList.contains('ck-launcher-blocked')!==blocked)launcher.classList.toggle('ck-launcher-blocked',blocked);if(blocked)close(false);}
 new MutationObserver(overlays).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class','hidden']});
 const viewport=window.visualViewport;function viewportSize(){if(viewport){panel.style.setProperty('--chat-height',Math.max(220,viewport.height-24)+'px');backdrop.style.top=viewport.offsetTop+'px';backdrop.style.height=viewport.height+'px';}}viewport?.addEventListener('resize',viewportSize);viewport?.addEventListener('scroll',viewportSize);viewportSize();sync();
})();
